import { CurrencyCode, CurrencyEntry, NumberProperties } from './types';

export const currencies: Record<CurrencyCode, CurrencyEntry> = {
  SDG: {
    singular: 'جنيه سوداني',
    dual: 'جنيهان سودانيان',
    plural: 'جنيهات سودانية',
    gender: 'm',
    fraction: 'قرش',
    fractionDual: 'قرشان',
    fractions: 'قروش',
    fractionGender: 'm',
    decimals: 2,
  },
  SAR: {
    singular: 'ريال سعودي',
    dual: 'ريالان سعوديان',
    plural: 'ريالات سعودية',
    gender: 'm',
    fraction: 'هللة',
    fractionDual: 'هللتان',
    fractions: 'هللات',
    fractionGender: 'f',
    decimals: 2,
  },
  QAR: {
    singular: 'ريال قطري',
    dual: 'ريالان قطريان',
    plural: 'ريالات قطرية',
    gender: 'm',
    fraction: 'درهم',
    fractionDual: 'درهمان',
    fractions: 'دراهم',
    fractionGender: 'm',
    decimals: 2,
  },
  AED: {
    singular: 'درهم إماراتي',
    dual: 'درهمان إماراتيان',
    plural: 'دراهم إماراتية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 2,
  },
  EGP: {
    singular: 'جنيه مصري',
    dual: 'جنيهان مصريان',
    plural: 'جنيهات مصرية',
    gender: 'm',
    fraction: 'قرش',
    fractionDual: 'قرشان',
    fractions: 'قروش',
    fractionGender: 'm',
    decimals: 2,
  },
  KWD: {
    singular: 'دينار كويتي',
    dual: 'ديناران كويتيان',
    plural: 'دنانير كويتية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 3,
  },
  USD: {
    singular: 'دولار أمريكي',
    dual: 'دولاران أمريكيان',
    plural: 'دولارات أمريكية',
    gender: 'm',
    fraction: 'سنت',
    fractionDual: 'سنتان',
    fractions: 'سنتات',
    fractionGender: 'm',
    decimals: 2,
  },
  AUD: {
    singular: 'دولار أسترالي',
    dual: 'دولاران أستراليان',
    plural: 'دولارات أسترالية',
    gender: 'm',
    fraction: 'سنت',
    fractionDual: 'سنتان',
    fractions: 'سنتات',
    fractionGender: 'm',
    decimals: 2,
  },
  TND: {
    singular: 'دينار تونسي',
    dual: 'ديناران تونسيان',
    plural: 'دنانير تونسية',
    gender: 'm',
    fraction: 'مليم',
    fractionDual: 'مليمان',
    fractions: 'مليمات',
    fractionGender: 'm',
    decimals: 3,
  },
  TRY: {
    singular: 'ليرة تركية',
    dual: 'ليرتان تركيتان',
    plural: 'ليرات تركية',
    gender: 'f',
    fraction: 'قرش',
    fractionDual: 'قرشان',
    fractions: 'قروش',
    fractionGender: 'm',
    decimals: 2,
  },
  BHD: {
    singular: 'دينار بحريني',
    dual: 'ديناران بحرينيان',
    plural: 'دنانير بحرينية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 3,
  },
  OMR: {
    singular: 'ريال عماني',
    dual: 'ريالان عمانيان',
    plural: 'ريالات عمانية',
    gender: 'm',
    fraction: 'بيسة',
    fractionDual: 'بيستان',
    fractions: 'بيسات',
    fractionGender: 'f',
    decimals: 3,
  },
  JOD: {
    singular: 'دينار أردني',
    dual: 'ديناران أردنيان',
    plural: 'دنانير أردنية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 3,
  },
  IQD: {
    singular: 'دينار عراقي',
    dual: 'ديناران عراقيان',
    plural: 'دنانير عراقية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 3,
  },
  LYD: {
    singular: 'دينار ليبي',
    dual: 'ديناران ليبيان',
    plural: 'دنانير ليبية',
    gender: 'm',
    fraction: 'درهم',
    fractionDual: 'درهمان',
    fractions: 'دراهم',
    fractionGender: 'm',
    decimals: 3,
  },
  LBP: {
    singular: 'ليرة لبنانية',
    dual: 'ليرتان لبنانيتان',
    plural: 'ليرات لبنانية',
    gender: 'f',
    fraction: 'قرش',
    fractionDual: 'قرشان',
    fractions: 'قروش',
    fractionGender: 'm',
    decimals: 2,
  },
  MAD: {
    singular: 'درهم مغربي',
    dual: 'درهمان مغربيان',
    plural: 'دراهم مغربية',
    gender: 'm',
    fraction: 'سنتيم',
    fractionDual: 'سنتيمان',
    fractions: 'سنتيمات',
    fractionGender: 'm',
    decimals: 2,
  },
  DZD: {
    singular: 'دينار جزائري',
    dual: 'ديناران جزائريان',
    plural: 'دنانير جزائرية',
    gender: 'm',
    fraction: 'سنتيم',
    fractionDual: 'سنتيمان',
    fractions: 'سنتيمات',
    fractionGender: 'm',
    decimals: 2,
  },
  SYP: {
    singular: 'ليرة سورية',
    dual: 'ليرتان سوريتان',
    plural: 'ليرات سورية',
    gender: 'f',
    fraction: 'قرش',
    fractionDual: 'قرشان',
    fractions: 'قروش',
    fractionGender: 'm',
    decimals: 2,
  },
  YER: {
    singular: 'ريال يمني',
    dual: 'ريالان يمنيان',
    plural: 'ريالات يمنية',
    gender: 'm',
    fraction: 'فلس',
    fractionDual: 'فلسان',
    fractions: 'فلوس',
    fractionGender: 'm',
    decimals: 2,
  },
  EUR: {
    singular: 'يورو',
    dual: 'يوروان',
    plural: 'يورو',
    gender: 'm',
    fraction: 'سنت',
    fractionDual: 'سنتان',
    fractions: 'سنتات',
    fractionGender: 'm',
    decimals: 2,
  },
  GBP: {
    singular: 'جنيه إسترليني',
    dual: 'جنيهان إسترلينيان',
    plural: 'جنيهات إسترلينية',
    gender: 'm',
    fraction: 'بنس',
    fractionDual: 'بنسان',
    fractions: 'بنسات',
    fractionGender: 'm',
    decimals: 2,
  },
  CHF: {
    singular: 'فرنك سويسري',
    dual: 'فرنكان سويسريان',
    plural: 'فرنكات سويسرية',
    gender: 'm',
    fraction: 'سنتيم',
    fractionDual: 'سنتيمان',
    fractions: 'سنتيمات',
    fractionGender: 'm',
    decimals: 2,
  },
  CAD: {
    singular: 'دولار كندي',
    dual: 'دولاران كنديان',
    plural: 'دولارات كندية',
    gender: 'm',
    fraction: 'سنت',
    fractionDual: 'سنتان',
    fractions: 'سنتات',
    fractionGender: 'm',
    decimals: 2,
  },
};

export const columns: readonly string[] = ['trillions', 'billions', 'millions', 'thousands'];

export const SUPPORTED_CURRENCIES: readonly CurrencyCode[] = Object.freeze([
  'AED',
  'AUD',
  'BHD',
  'CAD',
  'CHF',
  'DZD',
  'EGP',
  'EUR',
  'GBP',
  'IQD',
  'JOD',
  'KWD',
  'LBP',
  'LYD',
  'MAD',
  'OMR',
  'QAR',
  'SAR',
  'SDG',
  'SYP',
  'TND',
  'TRY',
  'USD',
  'YER',
]);

export const ONES: Readonly<Record<number, string>> = Object.freeze({
  1: 'واحد',
  2: 'اثنان',
  3: 'ثلاثة',
  4: 'أربعة',
  5: 'خمسة',
  6: 'ستة',
  7: 'سبعة',
  8: 'ثمانية',
  9: 'تسعة',
});

export const ONES_F: Readonly<Record<number, string>> = Object.freeze({
  1: 'إحدى',
  2: 'اثنتان',
  3: 'ثلاث',
  4: 'أربع',
  5: 'خمس',
  6: 'ست',
  7: 'سبع',
  8: 'ثماني',
  9: 'تسع',
});

export const TEENS: Readonly<Record<number, string>> = Object.freeze({
  11: 'أحد عشر',
  12: 'اثنا عشر',
  13: 'ثلاثة عشر',
  14: 'أربعة عشر',
  15: 'خمسة عشر',
  16: 'ستة عشر',
  17: 'سبعة عشر',
  18: 'ثمانية عشر',
  19: 'تسعة عشر',
});

export const TEENS_F: Readonly<Record<number, string>> = Object.freeze({
  11: 'إحدى عشرة',
  12: 'اثنتا عشرة',
  13: 'ثلاث عشرة',
  14: 'أربع عشرة',
  15: 'خمس عشرة',
  16: 'ست عشرة',
  17: 'سبع عشرة',
  18: 'ثماني عشرة',
  19: 'تسع عشرة',
});

export const TENS: Readonly<Record<number, string>> = Object.freeze({
  10: 'عشرة',
  20: 'عشرون',
  30: 'ثلاثون',
  40: 'أربعون',
  50: 'خمسون',
  60: 'ستون',
  70: 'سبعون',
  80: 'ثمانون',
  90: 'تسعون',
});

export const HUNDREDS: Readonly<Record<number, string>> = Object.freeze({
  100: 'مائة',
  200: 'مائتان',
  300: 'ثلاثمائة',
  400: 'أربعمائة',
  500: 'خمسمائة',
  600: 'ستمائة',
  700: 'سبعمائة',
  800: 'ثمانمائة',
  900: 'تسعمائة',
});

export const THOUSANDS: Readonly<NumberProperties> = Object.freeze({
  singular: 'ألف',
  binary: 'ألفان',
  plural: 'آلاف',
});

export const MILLIONS: Readonly<NumberProperties> = Object.freeze({
  singular: 'مليون',
  binary: 'مليونان',
  plural: 'ملايين',
});

export const BILLIONS: Readonly<NumberProperties> = Object.freeze({
  singular: 'مليار',
  binary: 'ملياران',
  plural: 'مليارات',
});

export const TRILLIONS: Readonly<NumberProperties> = Object.freeze({
  singular: 'تريليون',
  binary: 'تريليونان',
  plural: 'تريليونات',
});

export const COLUMN_PROPERTIES: Readonly<Record<string, Readonly<NumberProperties>>> = Object.freeze({
  trillions: TRILLIONS,
  billions: BILLIONS,
  millions: MILLIONS,
  thousands: THOUSANDS,
});
